name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create work dir
          mkdir gh-pages
          cp -r docs/* gh-pages/

          cd gh-pages
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy docs"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin gh-pages
